version: '3.7'
services:
  app:
    build:
      context: docker
      dockerfile: Dockerfile_hotspot
    ports:
      - "8080"
    volumes:
      - shareclasses:/opt/shareclasses
volumes:
  shareclasses: